name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      -
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 8
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '8'
      -
        name: "Build nb-javac"
        run: "ant -f ./make/langtools/netbeans/nb-javac clean jar"

      - name: Upload built jars
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: nb-javac
          path: make/langtools/netbeans/nb-javac/dist
